[data_store.sqlite]
db_url = "/var/lib/rustical/db.sqlite3"

[dav_push]
enabled = true

[frontend]
allow_password_login = false
enabled = true

[http]
host = "0.0.0.0"
port = 58443

[nextcloud_login]
enabled = false

[tracing]
opentelemetry = false
